Folia support
plan-player-analytics/Plan pull request #3617
Opened 2024-05-14 08:33 UTC by ColdeZhang

### Your checklist for this pull request
🚨 Please review the [guidelines for contributing](https://github.com/plan-player-analytics/Plan/blob/master/CONTRIBUTING.md#writing-a-good-pull-request) to this repository.

- [x] Make sure your name is added to Contributors file `/Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java`
- [x] If PR:ing locale changes also add a LangCode with your name `/Plan/common/src/main/java/com/djrapitops/plan/settings/locale/LangCode.java`

### Description
Add support for folia!

Noted: It needs to merge mu update for [Platform-abstraction-layer](https://github.com/plan-player-analytics/Platform-abstraction-layer/pull/2)  it add an new abstract layer for folia.

2024-05-14 09:41 UTC, AuroraLS3 commented
This is an interesting surprise, thanks!

Looks like there are ~100-200 bukkit based servers running Java version <17 which this PR drops support for. 

If there is some way to retain support for them I'd like to consider it - one option could be placing the folia code in new gradle module and using reflection to create the FoliaPlatformLayer instance in the bukkit module - I'm not 100% sure if gradle allows that sort of thing

I'll review these two PRs when I have the time, thanks!

2024-05-14 09:58 UTC, ColdeZhang commented
> one option could be placing the folia code in new gradle module and using reflection to create the FoliaPlatformLayer instance in the bukkit module

That's a good idea. I will try this method later!

2024-05-14 15:13 UTC, ColdeZhang commented
After consulting the relevant information and making some attempts...

Yes, maybe it could be compatible both 11 and 17 with different libs, but it's too complicateed to done. In contrast, the effort made is much higher than the harvest, and the cost performance is too low.

I choose to give up on this attemption, it's more than I can handle. :(

If Plan insist on looking back to under java17 servers, mybe this merge should be postponed, until the number of servers using older versions of Java is negligible.

2024-05-14 15:17 UTC, AuroraLS3 commented
Thanks for trying it out! Could you tell me what you attempted so that I can avoid repeating those attempts? :)

2024-05-14 16:32 UTC, ColdeZhang commented
1. do not compile `shadow "net.playeranalytics:platform-abstraction-layer-folia:$palVersion"`, but package it in to jar.
2. change codes into below, use reflection to load this class when java version is 17 and running on folia server.
```
    public void onLoad() {
        if (isJava17OrLater() && isFolia()) {
            try {
                // Attempt to load and use the Folia library for Java 17
                Class<?> foliaPlatformLayer = Class.forName("net.playeranalytics.plugin.FoliaPlatformLayer");
                abstractionLayer = (PlatformAbstractionLayer) foliaPlatformLayer.getConstructor(PlanPlugin.class).newInstance(this);
            } catch (Exception e) {
                this.getLogger().log(Level.SEVERE, "Failed to load FoliaPlatformLayer", e);
                abstractionLayer = new BukkitPlatformLayer(this);
            }
        } else {
            abstractionLayer = new BukkitPlatformLayer(this);
        }
        pluginLogger = abstractionLayer.getPluginLogger();
        runnableFactory = abstractionLayer.getRunnableFactory();
    }
```
3. Theoretically, this is possible.

Howerver, here is the problem I encountered......

1. I didnt figure out how to controll gradle just 'package' lib instead of 'compile' it. Whatever I tried, gradle still check the java versions and then throw errs.
2. I tried to put lib into servers 'libriries' folder directly, I assume mc should load libs in that folder. But it still doesnt work. 

:(

2024-05-14 16:57 UTC, AuroraLS3 commented
Alright, I think trying this option in the folia module might do something, not sure https://docs.gradle.org/current/kotlin-dsl/gradle/org.gradle.api.plugins/-java-plugin-convention/disable-auto-target-jvm.html

It might also be possible to try include the folia module in the plugin module instead of bukkit module

2024-05-15 01:56 UTC, ColdeZhang commented
> Alright, I think trying this option in the folia module might do something, not sure https://docs.gradle.org/current/kotlin-dsl/gradle/org.gradle.api.plugins/-java-plugin-convention/disable-auto-target-jvm.html
> 
> It might also be possible to try include the folia module in the plugin module instead of bukkit module
> 
> (This whole comment assumes a new folia module is added to Plan project)

wow, thanks for this information. it works now. I tested it on paper 1.16.5(java11) and folia 1.20.4(java17), both of them can loaded Plan proply.

![image](https://github.com/plan-player-analytics/Plan/assets/29792376/c56971dc-8cef-4e8c-8b40-d81b0071025d)
![image](https://github.com/plan-player-analytics/Plan/assets/29792376/3c37e7b0-878b-4db6-a48a-ac41f9b297fe)

2024-05-16 12:32 UTC, ColdeZhang commented
I did some test about CI-CD, it failed on 'aggregateJavadocs' step.
The problem is still about the jvm versions,

```
* What went wrong:
Execution failed for task ':aggregateJavadocs'.
> Could not resolve all files for configuration ':plugin:compileClasspath'.
   > Could not resolve net.playeranalytics:platform-abstraction-layer-folia:5.2.0.
     Required by:
         project :plugin > project :bukkit
      > No matching variant of net.playeranalytics:platform-abstraction-layer-folia:5.2.0 was found. The consumer was configured to find a library for use during compile-time, compatible with Java 11, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally but:
          - Variant 'apiElements' declares a library for use during compile-time, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 17 and the consumer needed a component, compatible with Java 11
              - Other compatible attribute:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
          - Variant 'runtimeElements' declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 17 and the consumer needed a component, compatible with Java 11
              - Other compatible attribute:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
```

2024-05-16 12:34 UTC, AuroraLS3 commented
Javadoc building fails, folia needs it's own gradle module, with pal-folia as dependency, and then that module would be shadowed in :plugin module, so that :bukkit module doesn't have Java 17 dependencies

The folia module doesn't need any Java files inside it as far as I'm aware

2024-05-16 14:04 UTC, AnttiMK commented
Do we want to move Folia's PAL into this repository as was done with Fabric, or keep it as is?

2024-05-16 14:21 UTC, AuroraLS3 commented
It's fine to keep as is, just the dependency needs to be moved :)

I think fabric was more involved since it included all sorts of other things on top of PAL that would make it seem disingenuous if PAL contained fabric, while it seems to work fine for Folia

2024-05-16 18:20 UTC, AnttiMK requested changes
Some little things, also have to make sure all scheduled stuff works correctly but code-wise lgtm

2024-05-16 18:20 UTC, AnttiMK commented on Plan/folia/build.gradle
> +}
```suggestion
}

```

2024-05-16 18:20 UTC, AnttiMK commented on Plan/bukkit/src/main/java/com/djrapitops/plan/Plan.java
> +        if (isJava17OrLater() && isFolia()) {
```suggestion
        if (isFolia()) {
```
Folia itself requires Java 17+ so this check is redundant

2024-05-16 18:20 UTC, AnttiMK commented on Plan/bukkit/src/main/java/com/djrapitops/plan/Plan.java
> +        return version.startsWith("17") || version.compareTo("17") > 0;
```suggestion
```
See above

2024-05-16 18:32 UTC, ColdeZhang commented
> Some little things, also have to make sure all scheduled stuff works correctly but code-wise lgtm

There still have javadoc problem, folia module can't pass 'aggregateJavadocs' step.

2024-05-17 03:41 UTC, ColdeZhang commented
Oky, here is the dilemma now:
1. The plugin `nebula aggregate-javadocs` project used doesn't support configure an exclude sub proj. (So can't make it ignore folia sub module)
2. Which worse is it's **Public archived** since Mar 1, 2021. (Means it will not support exclude function forever)

Two options:
1. Use another aggregate-javadocs plugin. (Not sure how many works need todo to migration)
2. Fork `nebula aggregate-javadocs` to support exclude function. (Easiest way, just need to add a flag in folia sub module. But upload plugin fork to maven central will take few more days.)

2024-05-17 17:31 UTC, AuroraLS3 commented
Alright, Looks like the folia module is redundant (and can be removed).

All the funky dependency business can be done in the plugin module

```gradle
dependencies {
    ...
    shadow "net.playeranalytics:platform-abstraction-layer-folia:$palVersion"
}

java {
    // This is required to prevent the shadow plugin from
    // adding the folia platform abstraction layer to the runtime classpath
    disableAutoTargetJvm()
}
```

I didn't have Folia installed so I couldn't test if that starts up, but at least Plan starts with Java 11 with this setup, and aggregateJavadocs works too.

2024-05-18 02:53 UTC, ColdeZhang commented
> Alright, Looks like the folia module is redundant (and can be removed).
> 
> All the funky dependency business can be done in the plugin module
> 
> ```groovy-gradle
> dependencies {
>     ...
>     shadow "net.playeranalytics:platform-abstraction-layer-folia:$palVersion"
> }
> 
> java {
>     // This is required to prevent the shadow plugin from
>     // adding the folia platform abstraction layer to the runtime classpath
>     disableAutoTargetJvm()
> }
> ```
> 
> I didn't have Folia installed so I couldn't test if that starts up, but at least Plan starts with Java 11 with this setup, and aggregateJavadocs works too.

This will also work. But I think disabling jvm inspections directly in the plugin is too aggressive and potentially dangerous.

To pass javadocs aggregate, I changed shadow to runtimeOnly:

```
dependencies {
    shadow "net.playeranalytics:platform-abstraction-layer-folia:$palVersion"
}
```
⬇️
```
dependencies {
    runtimeOnly "net.playeranalytics:platform-abstraction-layer-folia:$palVersion"
}
```

So this pal won't be involved in to aggregateJavadocs progress.

2024-05-18 07:06 UTC, AuroraLS3 commented
It looks like chrome driver got updated to be more shit, I'll try to sort out the problems with the AccessControlVisibilityTest

2024-05-18 07:08 UTC, ColdeZhang commented
I have a small question, why does the test phase pass when I build locally, but I get an error on the Github Actions CI? 

[https://pastes.dev/oobEreU7Lv](https://pastes.dev/oobEreU7Lv)

2024-05-18 07:09 UTC, ColdeZhang commented
> It looks like chrome driver got updated to be more shit, I'll try to sort out the problems with the AccessControlVisibilityTest

I think that's the real problem I encountered. 

https://pastes.dev/oobEreU7Lv

2024-05-18 07:15 UTC, AuroraLS3 commented
There is some interference going on when the browser swaps between tests and the test user trying to load /manage page, leading to a 403 error for /v1/permissions and data not being loaded so the test case fails.

Seems to be because chrome driver got updated. (CI it always gets the newest one)

2024-05-18 07:23 UTC, AuroraLS3 commented
Ah the 403 comes from rate limiter

2024-05-18 07:46 UTC, AuroraLS3 commented
You can merge master to this branch and that should sort out the issue

2024-05-18 10:32 UTC, ColdeZhang commented
> You can merge master to this branch and that should sort out the issue

Great, it works now.

2024-05-18 15:13 UTC, AuroraLS3 approved these changes
Great work! :) I'll merge this after testing that it works one more time.

Building folia itself seems to be an hour job so feel free to test it as well 😅

I'd be interested in error free behavior of:

- Plugin enable on Folia
- Player join + Player leave adding a Session to the website
- Player join + Gamemode change + Nether portal + Player leave adding a Session with overworld time data in Survival and Creative, and nether data in creative
- Player join + Server shutdown + Server start adding a Session
- Server running for few minutes adding Player online count, TPS and other performance data to Performance tab

2024-05-18 15:41 UTC, ColdeZhang commented
> Great work! :) I'll merge this after testing that it works one more time.
> 
> Building folia itself seems to be an hour job so feel free to test it as well 😅
> 
> I'd be interested in error free behavior of:
> 
> * Plugin enable on Folia
> * Plugin reload /plan reload
> * Plugin disable
> * Player join + Player leave adding a Session to the website
> * Player join + Gamemode change + Nether portal + Player leave adding a Session with overworld time data in Survival and Creative, and nether data in creative
> * Player join + Server shutdown + Server start adding a Session
> * Server running for few minutes adding Player online count, TPS and other performance data to Performance tab

Here is the [folia I built my self](https://ssl.lunadeer.cn:14446/zhangyuheng/DeerFolia/releases/tag/1.20.4-2615826), if you want you can use this for test.

First three I have tested:

- [x] Plugin enable on Folia
- [x] Plugin reload /plan reload
- [x] Plugin disable

rest of those you can check on [my own server](https://ssl.lunadeer.cn:14453/server/bc496f10-dafb-4d92-9ffa-e131b1e72461/overview). I am using it for several days. Eveything looks great fine,

2024-05-18 15:46 UTC, AnttiMK commented
Folia is well available from official sources through Paper's downloads API, see for example https://api.papermc.io/v2/projects/folia/versions/1.20.4/builds/31/downloads/folia-1.20.4-31.jar

2024-05-18 15:50 UTC, ColdeZhang commented
> Tested:
> 
> * [x]  Plugin enable on Folia
> * [x]  Plugin reload /plan reload
> * [x]  Plugin disable
> * [x]  Player join + Player leave adding a Session to the website
> * [x]  Player join + Gamemode change + Nether portal + Player leave adding a Session with overworld time data in Survival and Creative, and nether data in creative
>   
>   * ⚠️ world change event doesn't seem to trigger, leaving behind a Session with only one world, I don't know if this is due to Folia related changes
> * [x]  Player join + Server shutdown + Server start adding a Session
> * [x]  Server running for few minutes adding Player online count, TPS and other performance data to Performance tab

> ⚠️ world change event doesn't seem to trigger, leaving behind a Session with only one world, I don't know if this is due to Folia related changes

Yes, this event is disabled on folia currently.

2024-05-18 15:51 UTC, AuroraLS3 commented
Alright then everything seems to be working as intended :)

2024-05-18 15:52 UTC, merged

2024-05-18 15:53 UTC, AuroraLS3 commented
Thank you for all the correspondence and quick changes, it has made it easy to get this PR to the finish line & Thanks to @AnttiMK for PR review :)

2024-05-18 15:58 UTC, ColdeZhang commented
![image](https://github.com/plan-player-analytics/Plan/assets/29792376/8b439665-b252-4426-b42d-9477890f14fd)

The whole changeDimension was rewrited by folia.

2024-05-18 15:59 UTC, AuroraLS3 commented
Hopefully they will eventually sort that out, until then I'll just put a disclaimer to the change log and wiki for Folia about this data being wrong

2024-11-09 08:11 UTC, 404forever1 commented
大佬，如果使用变量的话folia会报错

2024-11-09 10:35 UTC, ColdeZhang commented
> 大佬，如果使用变量的话folia会报错

能提供一下具体的报错信息么

2024-11-09 15:31 UTC, xiaoluofa commented
> > 大佬，如果使用变量的话folia会报错
> 
> 能提供一下具体的报错信息么

最新的issue